# Generated by Django 5.1.7 on 2025-05-26 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_id', models.IntegerField()),
                ('partyname', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'parties',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'players',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_name', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'seasons',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_photos/')),
            ],
            options={
                'db_table': 'teams',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tournament_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'db_table': 'tournaments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FantasyClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clubname', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.party')),
            ],
            options={
                'db_table': 'fantasy_clubs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FantasyResult',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('tour', models.IntegerField()),
                ('home_goals', models.IntegerField()),
                ('away_goals', models.IntegerField()),
                ('home_points', models.IntegerField()),
                ('away_points', models.IntegerField()),
                ('away_club', models.ForeignKey(db_column='away_club_id', on_delete=django.db.models.deletion.CASCADE, related_name='away_results', to='users.fantasyclub')),
                ('home_club', models.ForeignKey(db_column='home_club_id', on_delete=django.db.models.deletion.CASCADE, related_name='home_results', to='users.fantasyclub')),
                ('party', models.ForeignKey(db_column='party_id', on_delete=django.db.models.deletion.CASCADE, to='users.party')),
            ],
            options={
                'db_table': 'fantasy_results',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FantasyClubFootballer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fantasy_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.fantasyclub')),
                ('footballer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.player')),
            ],
            options={
                'db_table': 'fantasy_clubs_footballers',
                'managed': True,
                'unique_together': {('fantasy_club', 'footballer')},
            },
        ),
        migrations.CreateModel(
            name='Player_Season_Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals_scored', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('bonus', models.IntegerField(default=0)),
                ('bps', models.IntegerField(default=0)),
                ('clean_sheets', models.IntegerField(default=0)),
                ('creativity', models.FloatField(default=0)),
                ('ict_index', models.FloatField(default=0)),
                ('influence', models.FloatField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('own_goals', models.IntegerField(default=0)),
                ('penalties_missed', models.IntegerField(default=0)),
                ('penalties_saved', models.IntegerField(default=0)),
                ('red_cards', models.BooleanField(default=True)),
                ('saves', models.IntegerField(default=0)),
                ('yellow_cards', models.IntegerField(default=0)),
                ('total_points', models.IntegerField(default=0)),
                ('player', models.ForeignKey(db_column='player_id', on_delete=django.db.models.deletion.CASCADE, to='users.player')),
                ('season', models.ForeignKey(db_column='season_id', on_delete=django.db.models.deletion.CASCADE, to='users.season')),
                ('team', models.ForeignKey(db_column='team_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.team')),
            ],
            options={
                'db_table': 'player_season_stats',
                'managed': True,
                'unique_together': {('player', 'season', 'team')},
            },
        ),
    ]
